#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#

PREFIX = /usr/local

WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++

INC = 
CFLAGS = -march=native -Wlong-long -fopenmp -fPIC
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = -fopenmp -lGL

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -Wall -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = ./libmeshlibd.a

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2 -Wall
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = ./libmeshlib.a

LIB_FNAME = libmeshlib.a

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/meshcalc.o $(OBJDIR_DEBUG)/src/meshclean.o $(OBJDIR_DEBUG)/src/meshcreate.o $(OBJDIR_DEBUG)/src/meshdraw.o $(OBJDIR_DEBUG)/src/mesherror.o $(OBJDIR_DEBUG)/src/meshfilter.o $(OBJDIR_DEBUG)/src/meshload.o $(OBJDIR_DEBUG)/src/meshops.o $(OBJDIR_DEBUG)/src/meshsave.o $(OBJDIR_DEBUG)/src/meshtext.o $(OBJDIR_DEBUG)/src/meshtransform.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/meshcalc.o $(OBJDIR_RELEASE)/src/meshclean.o $(OBJDIR_RELEASE)/src/meshcreate.o $(OBJDIR_RELEASE)/src/meshdraw.o $(OBJDIR_RELEASE)/src/mesherror.o $(OBJDIR_RELEASE)/src/meshfilter.o $(OBJDIR_RELEASE)/src/meshload.o $(OBJDIR_RELEASE)/src/meshops.o $(OBJDIR_RELEASE)/src/meshsave.o $(OBJDIR_RELEASE)/src/meshtext.o $(OBJDIR_RELEASE)/src/meshtransform.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(AR) rcs $(OUT_DEBUG) $(OBJ_DEBUG)

$(OBJDIR_DEBUG)/src/meshcalc.o: src/meshcalc.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/meshcalc.c -o $(OBJDIR_DEBUG)/src/meshcalc.o

$(OBJDIR_DEBUG)/src/meshclean.o: src/meshclean.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/meshclean.c -o $(OBJDIR_DEBUG)/src/meshclean.o

$(OBJDIR_DEBUG)/src/meshcreate.o: src/meshcreate.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/meshcreate.c -o $(OBJDIR_DEBUG)/src/meshcreate.o

$(OBJDIR_DEBUG)/src/meshdraw.o: src/meshdraw.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/meshdraw.c -o $(OBJDIR_DEBUG)/src/meshdraw.o

$(OBJDIR_DEBUG)/src/mesherror.o: src/mesherror.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/mesherror.c -o $(OBJDIR_DEBUG)/src/mesherror.o

$(OBJDIR_DEBUG)/src/meshfilter.o: src/meshfilter.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/meshfilter.c -o $(OBJDIR_DEBUG)/src/meshfilter.o

$(OBJDIR_DEBUG)/src/meshload.o: src/meshload.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/meshload.c -o $(OBJDIR_DEBUG)/src/meshload.o

$(OBJDIR_DEBUG)/src/meshops.o: src/meshops.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/meshops.c -o $(OBJDIR_DEBUG)/src/meshops.o

$(OBJDIR_DEBUG)/src/meshsave.o: src/meshsave.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/meshsave.c -o $(OBJDIR_DEBUG)/src/meshsave.o

$(OBJDIR_DEBUG)/src/meshtext.o: src/meshtext.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/meshtext.c -o $(OBJDIR_DEBUG)/src/meshtext.o

$(OBJDIR_DEBUG)/src/meshtransform.o: src/meshtransform.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/meshtransform.c -o $(OBJDIR_DEBUG)/src/meshtransform.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf $(OBJDIR_DEBUG)/src

before_release: 
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(AR) rcs $(OUT_RELEASE) $(OBJ_RELEASE)

$(OBJDIR_RELEASE)/src/meshcalc.o: src/meshcalc.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/meshcalc.c -o $(OBJDIR_RELEASE)/src/meshcalc.o

$(OBJDIR_RELEASE)/src/meshclean.o: src/meshclean.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/meshclean.c -o $(OBJDIR_RELEASE)/src/meshclean.o

$(OBJDIR_RELEASE)/src/meshcreate.o: src/meshcreate.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/meshcreate.c -o $(OBJDIR_RELEASE)/src/meshcreate.o

$(OBJDIR_RELEASE)/src/meshdraw.o: src/meshdraw.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/meshdraw.c -o $(OBJDIR_RELEASE)/src/meshdraw.o

$(OBJDIR_RELEASE)/src/mesherror.o: src/mesherror.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/mesherror.c -o $(OBJDIR_RELEASE)/src/mesherror.o

$(OBJDIR_RELEASE)/src/meshfilter.o: src/meshfilter.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/meshfilter.c -o $(OBJDIR_RELEASE)/src/meshfilter.o

$(OBJDIR_RELEASE)/src/meshload.o: src/meshload.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/meshload.c -o $(OBJDIR_RELEASE)/src/meshload.o

$(OBJDIR_RELEASE)/src/meshops.o: src/meshops.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/meshops.c -o $(OBJDIR_RELEASE)/src/meshops.o

$(OBJDIR_RELEASE)/src/meshsave.o: src/meshsave.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/meshsave.c -o $(OBJDIR_RELEASE)/src/meshsave.o

$(OBJDIR_RELEASE)/src/meshtext.o: src/meshtext.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/meshtext.c -o $(OBJDIR_RELEASE)/src/meshtext.o

$(OBJDIR_RELEASE)/src/meshtransform.o: src/meshtransform.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/meshtransform.c -o $(OBJDIR_RELEASE)/src/meshtransform.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf $(OBJDIR_RELEASE)/src

install:
	mkdir -p $(PREFIX)/lib
	mkdir -p $(PREFIX)/include
	cp $(OUT_RELEASE) $(PREFIX)/lib/$(LIB_FNAME)
	cp include/meshlib.h $(PREFIX)/include/

uninstall:
	rm -f $(PREFIX)/lib/$(LIB_FNAME)
	rm -f $(PREFIX)/include/meshlib.h

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release install uninstall

